name: Build and push bunkerized-nginx

on:
  schedule:
    - cron: '30 1 * * *'
  push:
    branches: [dev, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
          - platform: linux/arm64/v8
          - platform: linux/386
          - platform: linux/arm/v7

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      # temp fix : can't use buildx + load because of manifest error
      # so we need to build the image the traditional way
      - name: Temp build to check security issues
        run: docker build -t bunkerized-nginx .
   
      - name: Run Trivy security scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bunkerized-nginx'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Run autotest
        run: docker run bunkerized-nginx test

      - name: Set variables
        run: |
          VER=$(cat VERSION | tr -d '\n')
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ matrix.platform }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Docker cache (dev)
        uses: actions/cache@v3
        if: github.ref == 'refs/heads/dev'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}${{ matrix.platform }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}${{ matrix.platform }}-buildx-

      - name: Setup Docker cache (master)
        uses: actions/cache@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: |
              /tmp/.buildx-cache
              /tmp/.ccache
          key: ${{ runner.os }}${{ matrix.platform }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}${{ matrix.platform }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push (dev)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/dev'
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: thelittlefireman/bunkerized-nginx:dev
          cache-from: type=local,src=/tmp/.ccache
          cache-to: type=local,dest=/tmp/.ccache-new
      
      - name: Build and push (master)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: thelittlefireman/bunkerized-nginx:latest,thelittlefireman/bunkerized-nginx:${{ env.VERSION }}
          cache-from: type=local,src=/tmp/.ccache
          cache-to: type=local,dest=/tmp/.ccache-new

      - name: Build and push Libressl version (master)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          file: Dockerfile_libressl
          platforms: ${{ matrix.platform }}
          push: true
          tags: thelittlefireman/bunkerized-nginx:libressl-latest,thelittlefireman/bunkerized-nginx:libressl-${{ env.VERSION }}
          cache-from: type=local,src=/tmp/.ccache
          cache-to: type=local,dest=/tmp/.ccache-new

      - name: Build and push Mainline version (master)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          file: Dockerfile_mainline
          platforms: ${{ matrix.platform }}
          push: true
          tags: thelittlefireman/bunkerized-nginx:mainline-latest,thelittlefireman/bunkerized-nginx:mainline-${{ env.VERSION }}
          cache-from: type=local,src=/tmp/.ccache
          cache-to: type=local,dest=/tmp/.ccache-new

      - name: Build and push Libressl and Mainline version (master)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          file: Dockerfile_mainline_libressl
          platforms: ${{ matrix.platform }}
          push: true
          tags: thelittlefireman/bunkerized-nginx:mainline-libressl-latest,thelittlefireman/bunkerized-nginx:mainline-libressl-${{ env.VERSION }}
          cache-from: type=local,src=/tmp/.ccache
          cache-to: type=local,dest=/tmp/.ccache-new

      - name: Move Docker cache (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          rm -rf /tmp/.ccache
          mv /tmp/.ccache-new /tmp/.ccache || true
          
      - name: Move Docker cache (master)
        if: github.ref == 'refs/heads/master'
        run: |
          rm -rf /tmp/.ccache
          mv /tmp/.ccache-new /tmp/.ccache || true